name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.1"

    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v5
      - run: luarocks install luasocket
      - run: luarocks install busted
      - run: luarocks install luacheck
      - run: luarocks make orbit-framework-dev-1.rockspec
      - run: luacheck src spec examples bin/orbit
      - run: busted spec

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check src spec examples bin/orbit
